### ISSUE TITLE
Dates are all grayed out

### ISSUE THREAD

**Issue by cvwebb** [Matsuuu/lit-flatpickr#5]
I'm pretty new to Flatpickr and especially Lit-Flatpickr. But when I'm using it, it functions the way it should but all of the dates are grayed out. Any idea why this might be? 
Using the default:
` <lit-flatpickr
      class="textinput date-picker"
        id="my-date-picker"
        altInput
        altFormat="F j, Y"
        dateFormat="Y-m-d H:i"
        enableTime: true
      >`

See screenshot [below.[](url)]
![Screen Shot 2021-02-04 at 1 21 28 PM](https://user-images.githubusercontent.com/755245/106941595-0c090000-66f1-11eb-8523-248073e7b4ea.png)

**Comment by Matsuuu** [comment]
Hi! 

I can confirm this is the case. I'll check out tomorrow what they've changed. Most likely has to do with the `enable` property

**Comment by Matsuuu** [comment]
Hi, Sorry for taking so long @cvwebb !

I've pushed a new release today and it should resolve the error :)
