### ISSUE TITLE
Not able bind onchange event to lit-flatpickr element

### ISSUE THREAD

**Issue by pa1raju** [Matsuuu/lit-flatpickr#6]
import 'lit-flatpickr';
import { html, LitElement } from 'lit-element';

class MyApp extends LitElement {
  getValue() {
    this.shadowRoot.querySelector('#my-date-picker').getValue();
  }

getSelectedDate(){
  console.log('selected date');
}

  render() {
    return html`
      <lit-flatpickr
        id="my-date-picker"
        altInput
        altFormat="F j, Y"
        dateFormat="Y-m-d"
        theme="material_orange"
        minDate="2020-01"
        maxDate="2020-12-31"
        @change="${this.getSelectedDate}"
      ></lit-flatpickr>
    `;
  }
}

getSelectedDate is not triggering at all, Can you help us how invoke hooks and methods of  lit-flatpickr

**Comment by Matsuuu** [comment]
The Flatpickr API takes the `onChange` hook as a parameter.

```javascript
render() {
    return html`<lit-flatpickr
      id="my-date-picker"
      altInput
      altFormat="F j, Y"
      dateFormat="Y-m-d"
      theme="material_orange"
      minDate="2020-01"
      maxDate="2020-12-31"
      .onChange="${this.getSelectedDate}"
    ></lit-flatpickr>`;
  }
```

**Comment by pa1raju** [comment]
thank you @Matsuuu. It was working now. can you help suggest how to place fa-calender icon to ease of identification text box.
